name: Enforce Branch Naming Convention

on:
  push:
    branches:
      - "**"

jobs:
  check-branch-name:
    runs-on: ["linux", "self-hosted", "ubuntu", "custom-runner", "docker"]
    steps:
      - name: Get Branch Name
        id: branch
        run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Validate Branch Name
        run: |
          if [[ ! "${{ env.branch_name }}" =~ ^(feature|bug|hotfix|chore|release)\/[a-zA-Z0-9._-]+$ && "${{ env.branch_name }}" != "develop" && "${{ env.branch_name }}" != "production" ]]; then
            echo "🚨 ERROR: Invalid branch name '${{ env.branch_name }}'."
            exit 1
          fi

